site_name: Cybersecurity Merit Badge
site_description: Scouting America Cybersecurity Merit Badge - 2.5 hour class
repo_url: https://github.com/TomConner/cybersecurity-merit-badge
repo_name: TomConner/cybersecurity-merit-badge
theme:
  name: material
  features:
    - navigation.tabs
    - content.code.annotate
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
plugins:
  - search
  - mkdocs-revealjs
nav:
  - Home: index.md
  - Slides: slides.md
  - Handouts:
      - "Password & MFA Activity": handouts/passwords-mfa-handout.md
      - "Phishing & Public Wi-Fi Activity": handouts/phishing-wifi-handout.md
      - "Cryptography Cipher Activity": handouts/crypto-cipher-handout.md
      - "IoT & Home Network Checklist": handouts/iot-home-network-handout.md
      - "Requirement Checklist": handouts/requirement-checklist.md
